apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whatsit-export
  namespace: whatsit
spec:
  replicas:
  template:
    metadata:
      labels:
        role: whatsit-export
        name: whatsit-export
    spec:
      containers:
      - image: gcr.io/whatsit-174908/whatsit-export:latest
        name: whatsit-export
        env:
        - name: PROJECTID
          value: whatsit-174908
        ports:
        - containerPort: 6379